### PR TITLE
Fix terminology, currying => partial application

### PR DESCRIPTION
**Pull request by terraboops**
I'm pretty sure the term for this is partial application, not currying. However, I'm not sure and I always get them mixed it up - so I read Wikipedia.

Correct me if I'm wrong, but if it were curried the resulting function call would be something like `box.children(likesPerUser)(updateUserLikes);`.

Source:
https://en.wikipedia.org/wiki/Currying#Contrast_with_partial_function_application

### CODE REVIEW

**Comment by raisedadead** [comment]
I think, `currying` is more popular in dev communities? And anyone reading this document are more likely to see it elsewhere, and hence it would make sense to keep it that way?

**Comment by terraboops** [comment]
They are not the same thing.

**Comment by Gabri3l** [comment]
I think this PR is valid and correct. There's a lot of loose currying in the dev community but that doesn't mean we should reinforce an incorrect use of its definition. Either way it's safer to say partial application as currying is a type of partial application so we can't go wrong.

**Comment by terraboops** [comment]
Closing PR for inactivity... Thanks for trying @Gabri3l 😉

**Pull request closed without merging**
